import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import {randomBytes} from 'node:crypto';
const html = await readFile(new URL('../dist/index.html',import.meta.url));
const compressionModule={exports:{}};
new Function('module','exports',await readFile(new URL('../vendor/fflate-0.8.2.umd.js',import.meta.url),'utf8'))(compressionModule,compressionModule.exports);
const server = createServer((req,res)=> {res.writeHead(200,{'Content-Type':'text/html'});res.end(html);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url = `http://127.0.0.1:${server.address().port}/`;
await mkdir('work/browser',{recursive:true});
const browser = await chromium.launch({headless:true});
const errors=[];
const external=[];
try {
  const page = await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(/^https?:/.test(request.url()) && !request.url().startsWith(url)) external.push(request.url());});
  page.on('dialog',dialog=>dialog.accept());
  await page.goto(url);
  await page.waitForSelector('.entry-pass');
  // Minimum-length predictable passwords must work; strength is advisory.
  const master='123123';
  const layer='qwerty';
  const note='Line one  exact spacing\n\tПривет 世界 🔐\n';
  await page.locator('#vaultName').fill('Recovery test');
  await page.locator('#masterKey').fill(master);
  await page.locator('#entries .entry-pass').fill(layer);
  await page.locator('.entry-pass-confirm').fill(layer);
  await page.locator('.entry-text').fill(note);
  await page.locator('#kdfProfile').selectOption({value:'fast'},{force:true});
  await page.locator('#makeBtn').click();
  await page.waitForFunction(()=>document.getElementById('verifyBtn').classList.contains('ok'),{},{timeout:60000});
  await page.waitForSelector('#progressModal.active',{state:'hidden'});
  await page.screenshot({path:'work/browser/create-desktop.png',fullPage:true});
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#downloadPngBtn').click();
  const png=await downloadPromise;
  await png.saveAs('work/browser/container.png');
  const rawPromise=page.waitForEvent('download');
  await page.locator('#downloadRawBtn').click();
  await (await rawPromise).saveAs('work/browser/container.llc');
  await page.locator('#tabRead').click();
  await page.locator('#fileIn').setInputFiles('work/browser/container.png');
  await page.waitForFunction(()=>document.getElementById('readStatusWork').textContent.includes('Container found'),{},{timeout:20000});
  await page.locator('#readPassword').fill(master);
  await page.locator('#readBtn').click();
  await page.waitForFunction(()=>!document.getElementById('readLayerField').classList.contains('hidden'));
  await page.locator('#readLayerPassword').fill(layer);
  await page.locator('#readBtn').click();
  await page.waitForFunction(()=>document.getElementById('readWorkPane').classList.contains('has-result'));
  assert.equal(await page.locator('#readout').textContent(),note);
  await page.screenshot({path:'work/browser/read-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'work/browser/read-mobile.png',fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
  // A replacement must invalidate a running decryption and its finalizers.
  await page.locator('#readLayerPassword').fill('another valid but wrong layer passphrase');
  await page.locator('#readBtn').click();
  await page.locator('#replaceImageBtn').click();
  await page.waitForTimeout(750);
  assert.equal(await page.locator('#readout').textContent(),'');
  assert(!(await page.locator('#readWorkPane').getAttribute('class')).includes('active'));
  await page.locator('#fileIn').setInputFiles('work/browser/container.llc');
  await page.waitForFunction(()=>document.getElementById('readWorkPane').classList.contains('active'));
  await page.locator('#readPassword').fill(master);
  await page.locator('#readBtn').click();
  await page.waitForFunction(()=>!document.getElementById('readLayerField').classList.contains('hidden'));
  await page.locator('#readLayerPassword').fill(layer);
  await page.locator('#readBtn').click();
  await page.waitForFunction(()=>document.getElementById('readWorkPane').classList.contains('has-result'));
  assert.equal(await page.locator('#readout').textContent(),note);
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#tabMake').click();
  await page.locator('#kdfProfile').selectOption({value:'ultra'},{force:true});
  await page.locator('#makeBtn').click();
  await page.locator('#cancelOperationBtn').click();
  await page.waitForTimeout(800);
  assert.equal(await page.locator('#masterKey').inputValue(),'');
  assert.equal(await page.locator('.entry-text').inputValue(),'');
  assert(!(await page.locator('#makeView').getAttribute('class')).includes('has-output'));
  // Compact transport must remain usable beyond optical capacity, including key-file protection.
  const largeNote = randomBytes(7000).toString('base64');
  await page.locator('#masterKey').fill(master);
  await page.locator('#entries .entry-pass').fill(layer);
  await page.locator('.entry-pass-confirm').fill(layer);
  await page.locator('.entry-text').fill(largeNote);
  await page.locator('#keyFileMenuBtn').click();
  const keyDownload = page.waitForEvent('download');
  await page.locator('#generateKeyFileBtn').click();
  await (await keyDownload).saveAs('work/browser/generated.llkey');
  assert((await page.locator('#keyFileMenuBtn').textContent()).includes('Confirm'));
  await page.locator('#makeBtn').click();
  assert(!(await page.locator('#progressModal').getAttribute('class')).includes('active'));
  await page.locator('#masterKeyFileInput').setInputFiles('work/browser/generated.llkey');
  await page.waitForFunction(()=>document.getElementById('keyFileMenuBtn').textContent.includes('attached'));
  await page.locator('#kdfProfile').selectOption({value:'fast'},{force:true});
  await page.locator('#makeBtn').click();
  await page.waitForFunction(()=>document.getElementById('makeStatus').textContent.includes('Too large for one Aztec'),{},{timeout:60000});
  await page.waitForSelector('#progressModal.active',{state:'hidden'});
  assert(await page.locator('#downloadPngBtn').isDisabled());
  const largeDownload=page.waitForEvent('download');
  await page.locator('#downloadRawBtn').click();
  await (await largeDownload).saveAs('work/browser/large.llc');
  assert((await readFile('work/browser/large.llc')).length>4096);
  const zipDownload=page.waitForEvent('download');
  await page.locator('#downloadZipBtn').click();
  await (await zipDownload).saveAs('work/browser/large.zip');
  const zipFiles=compressionModule.exports.unzipSync(await readFile('work/browser/large.zip'));
  assert.equal(Object.keys(zipFiles).length,3,'compact-only ZIP must contain RAW, TXT and settings');
  assert(!Object.keys(zipFiles).some(name=>/\.(png|svg)$/i.test(name)));
  const settings=Buffer.from(Object.entries(zipFiles).find(([name])=>name.endsWith('/settings.txt'))[1]).toString();
  assert(!settings.includes(master) && !settings.includes(layer) && !settings.includes(largeNote));
  await page.locator('#tabRead').click();
  await page.locator('#fileIn').setInputFiles('work/browser/large.llc');
  await page.waitForFunction(()=>document.getElementById('readWorkPane').classList.contains('compact-only'));
  await page.locator('#readPassword').fill(master);
  await page.locator('#readBtn').click();
  await page.waitForFunction(()=>!document.getElementById('readBtn').disabled);
  assert((await page.locator('#readLayerField').getAttribute('class')).includes('hidden'),'missing key file must not unlock');
  await page.locator('#readKeyFileInput').setInputFiles('work/browser/generated.llkey');
  await page.locator('#readBtn').click();
  await page.waitForFunction(()=>!document.getElementById('readLayerField').classList.contains('hidden'));
  await page.locator('#readLayerPassword').fill(layer);
  await page.locator('#readBtn').click();
  await page.waitForFunction(()=>document.getElementById('readWorkPane').classList.contains('has-result'));
  assert.equal(await page.locator('#readout').textContent(),largeNote);
  await page.screenshot({path:'work/browser/compact-desktop.png',fullPage:true});
  await page.locator('#resetCompactBtn').click();
  assert(!(await page.locator('#readWorkPane').getAttribute('class')).includes('active'));
  const offline = await browser.newPage();
  offline.on('pageerror',error=>errors.push(error.message));
  await offline.goto(new URL('../dist/index.html',import.meta.url).href);
  await offline.locator('#tabRead').click();
  await offline.locator('#fileIn').setInputFiles('work/browser/container.llc');
  await offline.waitForFunction(()=>document.getElementById('readWorkPane').classList.contains('active'));
  await offline.locator('#readPassword').fill(master);
  await offline.locator('#readBtn').click();
  await offline.waitForFunction(()=>!document.getElementById('readLayerField').classList.contains('hidden'));
  await offline.locator('#readLayerPassword').fill(layer);
  await offline.locator('#readBtn').click();
  await offline.waitForFunction(()=>document.getElementById('readWorkPane').classList.contains('has-result'));
  assert.equal(await offline.locator('#readout').textContent(),note,'file:// offline recovery');
  assert.deepEqual(errors,[]);
  assert.deepEqual(external,[]);
  console.log('Browser flow: PNG + RAW imports, master/layer/exact Unicode, mobile layout, cancel/reset, compact-only >4KiB, key-file enforcement, no external requests OK');
} catch(error) {
  for(const page of browser.contexts().flatMap(context=>context.pages())) {
    console.error('PAGE:',(await page.locator('body').innerText()).slice(-7000));
    await page.screenshot({path:'work/browser/failure.png',fullPage:true});
  }
  console.error({errors,external});throw error;
} finally {await browser.close();server.close();}
